[package]
name = "tails-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tails"
path = "src/main.rs"

[dependencies]
tails = { path = "../" }
structopt = "0.3.26"
toml = "0.8.6"
serde = { version = "1.0", features = ["derive"] }
